/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#d2a476",
        "on-secondary-fixed": "#1c1c1a",
        "tertiary": "#6a5b53",
        "on-tertiary-fixed-variant": "#51443c",
        "on-primary-container": "#5a3915",
        "on-error-container": "#93000a",
        "surface-bright": "#fff8f5",
        "secondary-fixed-dim": "#c8c6c3",
        "on-primary-fixed-variant": "#61401b",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#4b3e36",
        "inverse-on-surface": "#f7efec",
        "inverse-primary": "#eebd8e",
        "outline": "#82756a",
        "secondary-fixed": "#e5e2df",
        "on-surface": "#1e1b19",
        "surface-container-highest": "#e8e1de",
        "surface-container-high": "#eee7e3",
        "on-secondary-fixed-variant": "#474745",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#f3dfd3",
        "on-primary-fixed": "#2c1600",
        "surface": "#fff8f5",
        "background": "#fff8f5",
        "surface-dim": "#dfd9d5",
        "surface-tint": "#7c5730",
        "tertiary-container": "#bba99f",
        "tertiary-fixed-dim": "#d6c3b8",
        "inverse-surface": "#33302e",
        "surface-variant": "#e8e1de",
        "primary-fixed": "#ffdcbd",
        "on-background": "#1e1b19",
        "outline-variant": "#d4c4b7",
        "primary": "#7c5730",
        "on-secondary-container": "#636260",
        "error": "#ba1a1a",
        "secondary": "#5f5e5c",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#50453b",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#241913",
        "secondary-container": "#e2dfdc",
        "primary-fixed-dim": "#eebd8e",
        "surface-container": "#f4ece9",
        "surface-container-low": "#faf2ef",
        "on-error": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      fontFamily: {
        headline: ["Noto Serif"],
        body: ["Manrope"],
        label: ["Manrope"]
      },
    },
  },
  plugins: [],
}